export enum SocketEvent {
	PLAYER_CONNECTED = 'PLAYER_CONNECTED',
	PLAYER_DISCONNECTED = 'PLAYER_DISCONNECTED',
	HOST_DISCONNECTED = 'HOST_DISCONNECTED',
	GAME_STARTED = 'GAME_STARTED',
	GAME_ENDED = 'GAME_ENDED',
	GAME_MOVES = 'GAME_MOVES'
}